
# 1. Getting a runtime environment directly from Rest, used by Go service, not for frontend use.
GET http://localhost:2000/api/v2/runtimes

# 1. Sample Response
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 74
ETag: W/"4a-vfCKIvfEs5+jsbPSgEEAnt2k6Dw"
Date: Wed, 02 Feb 2022 20:40:16 GMT
Connection: close

[
  {
    "language": "python",
    "version": "3.9.4",
    "aliases": [
      "py",
      "py3",
      "python3"
    ]
  }
]

