# 1. Piston Api call to get the installed languages : will send back empty array if none present in the environment
GET http://localhost:8080/api/v1/compilers

# 1. Sample Result
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Wed, 02 Feb 2022 21:42:10 GMT
Content-Length: 85
Connection: close

{
  "result": [
    {
      "language": "python",
      "version": "3.9.4",
      "aliases": [
        "py",
        "py3",
        "python3"
      ]
    }
  ]
}
